import React, { createContext, useContext, useState, useCallback } from 'react';

const translations = {
  en: {
    // Navbar
    nav_brand: 'Locker Management',
    nav_dashboard: 'Dashboard',
    nav_users: 'Users',
    nav_students: 'Students',
    nav_lockers: 'Lockers',
    nav_assignments: 'Assignments',
    nav_my_locker: 'My Locker',
    nav_logout: 'Logout',
    nav_theme_dark: 'Switch to dark mode',
    nav_theme_light: 'Switch to light mode',

    // Login
    login_placeholder_email: 'Login',
    login_placeholder_password: 'Password',
    login_btn: 'Login',
    login_loading: 'Logging in...',
    login_failed: 'Login failed',

    // Dashboard
    dash_title: 'Dashboard',
    dash_subtitle: 'Real-time overview of your locker management system',
    dash_total_capacity: 'Total Capacity',
    dash_occupied: 'Occupied',
    dash_available: 'Available',
    dash_occupied_pct: 'Occupied',
    dash_used: 'Used',
    dash_free: 'Free',
    dash_students: 'Students',
    dash_lockers: 'Lockers',
    dash_assignments: 'Assignments',
    dash_users: 'Users',
    dash_recent: 'Recent Assignments',
    dash_view_all: 'View All →',
    dash_no_assignments: 'No assignments yet',
    dash_occupancy_floor: 'Occupancy by Floor',
    dash_view_lockers: 'View Lockers →',
    dash_no_lockers: 'No active lockers',
    dash_floor: 'Floor',
    dash_lockers_unit: 'lockers',
    dash_used_unit: 'used',
    dash_students_by_course: 'Students by Course',
    dash_course: 'Course',
    dash_students_unit: 'students',
    dash_loading: 'Loading dashboard...',
    dash_error: 'Failed to load dashboard data.',
    dash_locker: 'Locker',
    dash_active: 'Active',
    dash_released: 'Released',
    dash_just_now: 'Just now',
    dash_m_ago: 'm ago',
    dash_h_ago: 'h ago',
    dash_d_ago: 'd ago',

    // Students
    students_title: 'Students Management',
    students_add: '+ Add Student',
    students_edit: 'Edit Student',
    students_add_new: 'Add New Student',
    students_full_name: 'Full Name',
    students_group: 'Group',
    students_barcode: 'Barcode',
    students_course: 'Course',
    students_actions: 'Actions',
    students_search: 'Search by name, group, barcode...',
    students_all_groups: 'All Groups',
    students_all_courses: 'All Courses',
    students_course_unit: 'course',
    students_import_csv: 'Import CSV',
    students_loading: 'Loading students...',
    students_empty: 'No students found.',
    students_delete_title: 'Delete Student',
    students_delete_msg: 'Are you sure you want to delete "{name}"? This action cannot be undone.',
    students_delete_bulk_title: 'Delete Students',
    students_delete_bulk_msg: 'Are you sure you want to delete {count} student(s)? This action cannot be undone.',
    students_delete_selected: 'Delete {count} selected',
    students_failed_load: 'Failed to load students',
    students_failed_delete: 'Failed to delete student',
    students_failed_delete_n: 'Failed to delete {count} student(s)',
    students_op_failed: 'Operation failed',
    students_imported: 'Imported: {created} created, {skipped} skipped',
    students_csv_failed: 'CSV import failed',

    // Lockers
    lockers_title: 'Lockers Management',
    lockers_add: '+ Add Locker',
    lockers_edit: 'Edit Locker',
    lockers_add_new: 'Add New Locker',
    lockers_number: 'Number',
    lockers_size: 'Size',
    lockers_access: 'Access',
    lockers_capacity: 'Capacity',
    lockers_capacity_auto: 'Capacity (auto)',
    lockers_occupied: 'Occupied',
    lockers_floor: 'Floor',
    lockers_status: 'Status',
    lockers_availability: 'Availability',
    lockers_actions: 'Actions',
    lockers_search: 'Search by locker number...',
    lockers_all_floors: 'All Floors',
    lockers_all_sizes: 'All Sizes',
    lockers_all_status: 'All Status',
    lockers_all_avail: 'All Availability',
    lockers_small: 'Small',
    lockers_medium: 'Medium',
    lockers_large: 'Large',
    lockers_active: 'Active',
    lockers_inactive: 'Inactive',
    lockers_available: 'Available',
    lockers_full: 'Full',
    lockers_import_csv: 'Import CSV',
    lockers_loading: 'Loading lockers...',
    lockers_empty: 'No lockers found.',
    lockers_delete_title: 'Delete Locker',
    lockers_delete_msg: 'Are you sure you want to delete locker "{number}"? This action cannot be undone.',
    lockers_delete_bulk_title: 'Delete Lockers',
    lockers_delete_bulk_msg: 'Are you sure you want to delete {count} locker(s)? This action cannot be undone.',
    lockers_delete_selected: 'Delete {count} selected',
    lockers_failed_load: 'Failed to load lockers',
    lockers_failed_delete: 'Failed to delete locker',
    lockers_failed_delete_n: 'Failed to delete {count} locker(s)',
    lockers_op_failed: 'Operation failed',
    lockers_imported: 'Imported: {created} created, {skipped} skipped',
    lockers_csv_failed: 'CSV import failed',

    // Assignments
    assign_title: 'Assignments',
    assign_add: '+ Assign Locker',
    assign_btn: 'Assign',
    assign_form_title: 'Assign Locker to Student',
    assign_student: 'Student',
    assign_student_lc: 'student',
    assign_locker: 'Locker',
    assign_select_student: 'Select a student...',
    assign_select_locker: 'Select a locker...',
    assign_assigned_at: 'Assigned At',
    assign_released_at: 'Released At',
    assign_status: 'Status',
    assign_actions: 'Actions',
    assign_search: 'Search by student or locker...',
    assign_all_status: 'All Status',
    assign_active: 'Active',
    assign_released: 'Assignment released!',
    assign_released_label: 'Released',
    assign_release: 'Release',
    assign_loading: 'Loading assignments...',
    assign_empty: 'No assignments found.',
    assign_success: 'Locker assigned successfully!',
    assign_failed: 'Assignment failed',
    assign_release_failed: 'Release failed',
    assign_release_title: 'Release Assignment',
    assign_release_msg: 'Release locker "{locker}" from "{student}"?',
    assign_failed_load: 'Failed to load data',

    // Users
    users_title: 'Users',
    users_create_title: 'Create User Account',
    users_email: 'Email (university email)',
    users_password: 'Password',
    users_password_ph: 'Set a password',
    users_role: 'Role',
    users_role_user: 'User',
    users_role_admin: 'Admin',
    users_link_student: 'Link to Student',
    users_select_student: 'Select a student',
    users_user: 'User',
    users_admin: 'Admin',
    users_create_btn: 'Create & Send Credentials',
    users_creating: 'Creating...',
    users_student: 'Student',
    users_barcode: 'Barcode',
    users_actions: 'Actions',
    users_search: 'Search by email, student name, barcode...',
    users_empty: 'No users found',
    users_loading: 'Loading users...',
    users_delete_title: 'Delete User',
    users_delete_msg: 'Are you sure you want to delete user "{email}"? This action cannot be undone.',
    users_delete_bulk_title: 'Delete Users',
    users_delete_bulk_msg: 'Are you sure you want to delete {count} user(s)? This action cannot be undone.',
    users_delete_selected: 'Delete {count} selected',
    users_failed_load: 'Failed to load users',
    users_create_failed: 'Failed to create user',
    users_delete_failed: 'Failed to delete user',
    users_failed_delete_n: 'Failed to delete {count} user(s)',
    users_created_email: 'Account created for {email}. Credentials sent via email.',
    users_created_no_email: 'Account created for {email}, but email delivery failed. Please share credentials manually.',
    users_deleted: 'User {email} deleted.',
    users_deleted_n: '{count} user(s) deleted.',

    // User Dashboard
    ud_welcome: 'Welcome back!',
    ud_welcome_name: 'Welcome back, {name}!',
    ud_total: 'Total',
    ud_active: 'Active',
    ud_past: 'Past',
    ud_course: 'course',
    ud_active_locker: 'Your Active Locker',
    ud_your_locker: 'Your Active Locker',
    ud_floor: 'Floor',
    ud_size: 'Size',
    ud_access: 'Access',
    ud_capacity: 'Capacity',
    ud_assigned: 'Assigned',
    ud_duration: 'Duration',
    ud_days: 'days',
    ud_no_locker: 'No Active Locker',
    ud_no_locker_desc: 'You do not have a locker assigned. Contact an administrator.',
    ud_history: 'Assignment History',
    ud_released: 'Released',
    ud_no_profile: 'No Student Profile Linked',
    ud_no_profile_desc: 'Your account is not linked to a student profile. Contact an administrator.',
    ud_no_student: 'No Student Profile Linked',
    ud_no_student_desc: 'Your account is not linked to a student profile. Contact an administrator.',
    ud_loading: 'Loading your dashboard...',
    ud_failed_load: 'Failed to load your dashboard',
    ud_error: 'Failed to load your dashboard',

    // Common
    btn_edit: 'Edit',
    btn_delete: 'Delete',
    btn_cancel: 'Cancel',
    btn_create: 'Create',
    btn_update: 'Update',
    btn_assign: 'Assign',
    btn_clear: 'Clear',
    btn_confirm: 'Confirm',
    results: 'Results',
    of: 'of',
    footer_up: 'Up',

    // Navbar extras
    nav_analytics: 'Analytics',
    nav_change_password: 'Change Password',

    // Maintenance
    lockers_maintenance: 'Maintenance',

    // Analytics
    analytics_loading: 'Loading analytics...',
    analytics_error: 'Failed to load analytics data.',
    analytics_title: 'Analytics',
    analytics_week: 'Week',
    analytics_month: 'Month',
    analytics_quarter: 'Quarter',
    analytics_total_capacity: 'Total Capacity',
    analytics_current_occupied: 'Occupied Now',
    analytics_current_rate: 'Occupancy Rate',
    analytics_maintenance: 'Maintenance',
    analytics_occupancy_trend: 'Occupancy Trend',
    analytics_activity: 'Activity',
    analytics_no_activity: 'No activity in this period.',
    analytics_new_assignments: 'New Assignments',
    analytics_releases: 'Releases',
    analytics_none: 'None',
    analytics_by_size: 'By Size',
    analytics_lockers: 'lockers',
    analytics_peak_days: 'Peak Days',
    analytics_assignments: 'assignments',

    // Password change
    pwd_title: 'Change Password',
    pwd_current: 'Current Password',
    pwd_new: 'New Password',
    pwd_confirm: 'Confirm New Password',
    pwd_save: 'Change Password',
    pwd_saving: 'Saving...',
    pwd_success: 'Password changed successfully!',
    pwd_failed: 'Failed to change password.',
    pwd_mismatch: 'New passwords do not match.',
    pwd_min_length: 'Password must be at least 6 characters.',

    // Combined CSV import
    csv_combined_import: 'Import Combined CSV',
    csv_combined_failed: 'Combined CSV import failed',
    csv_combined_result: 'Import complete: {students} students, {lockers} lockers, {assignments} assignments created, {skipped} skipped',
  },

  ru: {
    // Navbar
    nav_brand: 'Управление шкафчиками',
    nav_dashboard: 'Главная',
    nav_users: 'Пользователи',
    nav_students: 'Студенты',
    nav_lockers: 'Шкафчики',
    nav_assignments: 'Назначения',
    nav_my_locker: 'Мой шкафчик',
    nav_logout: 'Выйти',
    nav_theme_dark: 'Тёмная тема',
    nav_theme_light: 'Светлая тема',

    // Login
    login_placeholder_email: 'Логин',
    login_placeholder_password: 'Пароль',
    login_btn: 'Вход',
    login_loading: 'Вход...',
    login_failed: 'Ошибка входа',

    // Dashboard
    dash_title: 'Главная',
    dash_subtitle: 'Обзор системы управления шкафчиками в реальном времени',
    dash_total_capacity: 'Общая вместимость',
    dash_occupied: 'Занято',
    dash_available: 'Свободно',
    dash_occupied_pct: 'Занято',
    dash_used: 'Занято',
    dash_free: 'Свободно',
    dash_students: 'Студенты',
    dash_lockers: 'Шкафчики',
    dash_assignments: 'Назначения',
    dash_users: 'Пользователи',
    dash_recent: 'Последние назначения',
    dash_view_all: 'Все →',
    dash_no_assignments: 'Назначений пока нет',
    dash_occupancy_floor: 'Занятость по этажам',
    dash_view_lockers: 'К шкафчикам →',
    dash_no_lockers: 'Нет активных шкафчиков',
    dash_floor: 'Этаж',
    dash_lockers_unit: 'шкафч.',
    dash_used_unit: 'занято',
    dash_students_by_course: 'Студенты по курсам',
    dash_course: 'Курс',
    dash_students_unit: 'студ.',
    dash_loading: 'Загрузка панели...',
    dash_error: 'Не удалось загрузить данные.',
    dash_locker: 'Шкафчик',
    dash_active: 'Активно',
    dash_released: 'Освобождён',
    dash_just_now: 'Только что',
    dash_m_ago: 'мин назад',
    dash_h_ago: 'ч назад',
    dash_d_ago: 'дн назад',

    // Students
    students_title: 'Управление студентами',
    students_add: '+ Добавить студента',
    students_edit: 'Редактировать студента',
    students_add_new: 'Добавить нового студента',
    students_full_name: 'ФИО',
    students_group: 'Группа',
    students_barcode: 'Штрихкод',
    students_course: 'Курс',
    students_actions: 'Действия',
    students_search: 'Поиск по имени, группе, штрихкоду...',
    students_all_groups: 'Все группы',
    students_all_courses: 'Все курсы',
    students_course_unit: 'курс',
    students_import_csv: 'Импорт CSV',
    students_loading: 'Загрузка студентов...',
    students_empty: 'Студенты не найдены.',
    students_delete_title: 'Удалить студента',
    students_delete_msg: 'Вы уверены, что хотите удалить "{name}"? Это действие необратимо.',
    students_delete_bulk_title: 'Удалить студентов',
    students_delete_bulk_msg: 'Вы уверены, что хотите удалить {count} студент(ов)? Это действие необратимо.',
    students_delete_selected: 'Удалить {count} выбр.',
    students_failed_load: 'Не удалось загрузить студентов',
    students_failed_delete: 'Не удалось удалить студента',
    students_failed_delete_n: 'Не удалось удалить {count} студент(ов)',
    students_op_failed: 'Операция не удалась',
    students_imported: 'Импорт: {created} создано, {skipped} пропущено',
    students_csv_failed: 'Импорт CSV не удался',

    // Lockers
    lockers_title: 'Управление шкафчиками',
    lockers_add: '+ Добавить шкафчик',
    lockers_edit: 'Редактировать шкафчик',
    lockers_add_new: 'Добавить новый шкафчик',
    lockers_number: 'Номер',
    lockers_size: 'Размер',
    lockers_access: 'Доступ',
    lockers_capacity: 'Вместимость',
    lockers_capacity_auto: 'Вместимость (авто)',
    lockers_occupied: 'Занято',
    lockers_floor: 'Этаж',
    lockers_status: 'Статус',
    lockers_availability: 'Доступность',
    lockers_actions: 'Действия',
    lockers_search: 'Поиск по номеру шкафчика...',
    lockers_all_floors: 'Все этажи',
    lockers_all_sizes: 'Все размеры',
    lockers_all_status: 'Все статусы',
    lockers_all_avail: 'Вся доступность',
    lockers_small: 'Маленький',
    lockers_medium: 'Средний',
    lockers_large: 'Большой',
    lockers_active: 'Активный',
    lockers_inactive: 'Неактивный',
    lockers_available: 'Свободен',
    lockers_full: 'Занят',
    lockers_import_csv: 'Импорт CSV',
    lockers_loading: 'Загрузка шкафчиков...',
    lockers_empty: 'Шкафчики не найдены.',
    lockers_delete_title: 'Удалить шкафчик',
    lockers_delete_msg: 'Вы уверены, что хотите удалить шкафчик "{number}"? Это действие необратимо.',
    lockers_delete_bulk_title: 'Удалить шкафчики',
    lockers_delete_bulk_msg: 'Вы уверены, что хотите удалить {count} шкафчик(ов)? Это действие необратимо.',
    lockers_delete_selected: 'Удалить {count} выбр.',
    lockers_failed_load: 'Не удалось загрузить шкафчики',
    lockers_failed_delete: 'Не удалось удалить шкафчик',
    lockers_failed_delete_n: 'Не удалось удалить {count} шкафчик(ов)',
    lockers_op_failed: 'Операция не удалась',
    lockers_imported: 'Импорт: {created} создано, {skipped} пропущено',
    lockers_csv_failed: 'Импорт CSV не удался',

    // Assignments
    assign_title: 'Назначения',
    assign_add: '+ Назначить шкафчик',
    assign_btn: 'Назначить',
    assign_form_title: 'Назначить шкафчик студенту',
    assign_student: 'Студент',
    assign_student_lc: 'студент',
    assign_locker: 'Шкафчик',
    assign_select_student: 'Выберите студента...',
    assign_select_locker: 'Выберите шкафчик...',
    assign_assigned_at: 'Назначено',
    assign_released_at: 'Освобождено',
    assign_status: 'Статус',
    assign_actions: 'Действия',
    assign_search: 'Поиск по студенту или шкафчику...',
    assign_all_status: 'Все статусы',
    assign_active: 'Активно',
    assign_released: 'Назначение освобождено!',
    assign_released_label: 'Освобождён',
    assign_release: 'Освободить',
    assign_loading: 'Загрузка назначений...',
    assign_empty: 'Назначения не найдены.',
    assign_success: 'Шкафчик успешно назначен!',
    assign_failed: 'Ошибка назначения',
    assign_release_failed: 'Ошибка освобождения',
    assign_release_title: 'Освободить назначение',
    assign_release_msg: 'Освободить шкафчик "{locker}" от "{student}"?',
    assign_failed_load: 'Не удалось загрузить данные',

    // Users
    users_title: 'Пользователи',
    users_create_title: 'Создать аккаунт',
    users_email: 'Email (университетская почта)',
    users_password: 'Пароль',
    users_password_ph: 'Задайте пароль',
    users_role: 'Роль',
    users_role_user: 'Пользователь',
    users_role_admin: 'Администратор',
    users_link_student: 'Привязать к студенту',
    users_select_student: 'Выберите студента',
    users_user: 'Пользователь',
    users_admin: 'Администратор',
    users_create_btn: 'Создать и отправить данные',
    users_creating: 'Создание...',
    users_student: 'Студент',
    users_barcode: 'Штрихкод',
    users_actions: 'Действия',
    users_search: 'Поиск по email, имени студента, штрихкоду...',
    users_empty: 'Пользователи не найдены',
    users_loading: 'Загрузка пользователей...',
    users_delete_title: 'Удалить пользователя',
    users_delete_msg: 'Вы уверены, что хотите удалить пользователя "{email}"? Это действие необратимо.',
    users_delete_bulk_title: 'Удалить пользователей',
    users_delete_bulk_msg: 'Вы уверены, что хотите удалить {count} пользователей? Это действие необратимо.',
    users_delete_selected: 'Удалить {count} выбр.',
    users_failed_load: 'Не удалось загрузить пользователей',
    users_create_failed: 'Не удалось создать пользователя',
    users_delete_failed: 'Не удалось удалить пользователя',
    users_failed_delete_n: 'Не удалось удалить {count} пользователей',
    users_created_email: 'Аккаунт создан для {email}. Данные отправлены на email.',
    users_created_no_email: 'Аккаунт создан для {email}, но письмо не доставлено. Передайте данные вручную.',
    users_deleted: 'Пользователь {email} удалён.',
    users_deleted_n: '{count} пользователь(ей) удалено.',

    // User Dashboard
    ud_welcome: 'С возвращением!',
    ud_welcome_name: 'С возвращением, {name}!',
    ud_total: 'Всего',
    ud_active: 'Активно',
    ud_past: 'Прошлые',
    ud_course: 'курс',
    ud_active_locker: 'Ваш активный шкафчик',
    ud_your_locker: 'Ваш активный шкафчик',
    ud_floor: 'Этаж',
    ud_size: 'Размер',
    ud_access: 'Доступ',
    ud_capacity: 'Вместимость',
    ud_assigned: 'Назначен',
    ud_duration: 'Длительность',
    ud_days: 'дней',
    ud_no_locker: 'Нет активного шкафчика',
    ud_no_locker_desc: 'У вас нет назначенного шкафчика. Обратитесь к администратору.',
    ud_history: 'История назначений',
    ud_released: 'Освобождён',
    ud_no_profile: 'Профиль студента не привязан',
    ud_no_profile_desc: 'Ваш аккаунт не привязан к профилю студента. Обратитесь к администратору.',
    ud_no_student: 'Профиль студента не привязан',
    ud_no_student_desc: 'Ваш аккаунт не привязан к профилю студента. Обратитесь к администратору.',
    ud_loading: 'Загрузка панели...',
    ud_failed_load: 'Не удалось загрузить панель',
    ud_error: 'Не удалось загрузить панель',

    // Common
    btn_edit: 'Редакт.',
    btn_delete: 'Удалить',
    btn_cancel: 'Отмена',
    btn_create: 'Создать',
    btn_update: 'Обновить',
    btn_assign: 'Назначить',
    btn_clear: 'Очистить',
    btn_confirm: 'Подтвердить',
    results: 'Результаты',
    of: 'из',
    footer_up: 'Наверх',

    // Navbar extras
    nav_analytics: 'Аналитика',
    nav_change_password: 'Сменить пароль',

    // Maintenance
    lockers_maintenance: 'На обслуживании',

    // Analytics
    analytics_loading: 'Загрузка аналитики...',
    analytics_error: 'Не удалось загрузить аналитику.',
    analytics_title: 'Аналитика',
    analytics_week: 'Неделя',
    analytics_month: 'Месяц',
    analytics_quarter: 'Квартал',
    analytics_total_capacity: 'Общая вместимость',
    analytics_current_occupied: 'Занято сейчас',
    analytics_current_rate: 'Загруженность',
    analytics_maintenance: 'На обслуживании',
    analytics_occupancy_trend: 'Тренд занятости',
    analytics_activity: 'Активность',
    analytics_no_activity: 'Нет активности за этот период.',
    analytics_new_assignments: 'Новые назначения',
    analytics_releases: 'Освобождения',
    analytics_none: 'Нет',
    analytics_by_size: 'По размеру',
    analytics_lockers: 'шкафчиков',
    analytics_peak_days: 'Самые загруженные дни',
    analytics_assignments: 'назначений',

    // Password change
    pwd_title: 'Смена пароля',
    pwd_current: 'Текущий пароль',
    pwd_new: 'Новый пароль',
    pwd_confirm: 'Подтвердите новый пароль',
    pwd_save: 'Сменить пароль',
    pwd_saving: 'Сохранение...',
    pwd_success: 'Пароль успешно изменён!',
    pwd_failed: 'Не удалось сменить пароль.',
    pwd_mismatch: 'Новые пароли не совпадают.',
    pwd_min_length: 'Пароль должен быть не менее 6 символов.',

    // Combined CSV import
    csv_combined_import: 'Импорт общего CSV',
    csv_combined_failed: 'Ошибка импорта CSV',
    csv_combined_result: 'Импорт завершён: {students} студентов, {lockers} шкафчиков, {assignments} назначений создано, {skipped} пропущено',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en');

  const switchLang = useCallback((newLang) => {
    setLang(newLang);
    localStorage.setItem('lang', newLang);
  }, []);

  const t = useCallback((key, params) => {
    let text = translations[lang]?.[key] || translations.en[key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, v);
      });
    }
    return text;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, switchLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
