import React, { createContext, useContext, useState, useCallback } from 'react';

const translations = {
  en: {
    // Navbar
    nav_brand: 'AITU Locker',
    nav_dashboard: 'Dashboard',
    nav_users: 'Users',
    nav_students: 'Students',
    nav_lockers: 'Lockers',
    nav_assignments: 'Assignments',
    nav_my_locker: 'My Locker',
    nav_logout: 'Logout',
    nav_theme_dark: 'Switch to dark mode',
    nav_theme_light: 'Switch to light mode',

    // Login
    login_placeholder_email: 'Login',
    login_placeholder_password: 'Password',
    login_btn: 'Login',
    login_loading: 'Logging in...',
    login_failed: 'Login failed',

    // Dashboard
    dash_title: 'Dashboard',
    dash_subtitle: 'Real-time overview of your locker management system',
    dash_total_capacity: 'Total Capacity',
    dash_occupied: 'Occupied',
    dash_available: 'Available',
    dash_occupied_pct: 'Occupied',
    dash_used: 'Used',
    dash_free: 'Free',
    dash_students: 'Students',
    dash_lockers: 'Lockers',
    dash_assignments: 'Assignments',
    dash_users: 'Users',
    dash_recent: 'Recent Assignments',
    dash_view_all: 'View All →',
    dash_no_assignments: 'No assignments yet',
    dash_occupancy_floor: 'Occupancy by Floor',
    dash_view_lockers: 'View Lockers →',
    dash_no_lockers: 'No active lockers',
    dash_floor: 'Floor',
    dash_lockers_unit: 'lockers',
    dash_used_unit: 'used',
    dash_students_by_course: 'Students by Course',
    dash_course: 'Course',
    dash_students_unit: 'students',
    dash_loading: 'Loading dashboard...',
    dash_error: 'Failed to load dashboard data.',
    dash_locker: 'Locker',
    dash_active: 'Active',
    dash_released: 'Released',
    dash_just_now: 'Just now',
    dash_m_ago: 'm ago',
    dash_h_ago: 'h ago',
    dash_d_ago: 'd ago',

    // Students
    students_title: 'Students Management',
    students_add: '+ Add Student',
    students_edit: 'Edit Student',
    students_add_new: 'Add New Student',
    students_full_name: 'Full Name',
    students_group: 'Group',
    students_barcode: 'Barcode',
    students_course: 'Course',
    students_actions: 'Actions',
    students_search: 'Search by name, group, barcode...',
    students_all_groups: 'All Groups',
    students_all_courses: 'All Courses',
    students_all_statuses: 'All Statuses',
    students_inclusive_status: 'Inclusive Status',
    inclusive_none: 'No special status',
    inclusive_disability: 'Physical disability',
    inclusive_orphan: 'Orphan',
    inclusive_vision: 'Vision impairment',
    inclusive_hearing: 'Hearing impairment',
    inclusive_other: 'Other',
    inclusive_filter_priority: 'Priority students',
    students_course_unit: 'course',
    students_import_csv: 'Import CSV',
    students_loading: 'Loading students...',
    students_empty: 'No students found.',
    students_delete_title: 'Delete Student',
    students_delete_msg: 'Are you sure you want to delete "{name}"? This action cannot be undone.',
    students_delete_bulk_title: 'Delete Students',
    students_delete_bulk_msg: 'Are you sure you want to delete {count} student(s)? This action cannot be undone.',
    students_delete_selected: 'Delete {count} selected',
    students_failed_load: 'Failed to load students',
    students_failed_delete: 'Failed to delete student',
    students_failed_delete_n: 'Failed to delete {count} student(s)',
    students_op_failed: 'Operation failed',
    students_imported: 'Imported: {created} created, {skipped} skipped',
    students_csv_failed: 'CSV import failed',

    // Lockers
    lockers_title: 'Lockers Management',
    lockers_add: ' Add Locker',
    lockers_edit: 'Edit Locker',
    lockers_add_new: 'Add New Locker',
    lockers_number: 'Number',
    lockers_size: 'Size',
    lockers_access: 'Access',
    lockers_capacity: 'Capacity',
    lockers_capacity_auto: 'Capacity (auto)',
    lockers_occupied: 'Occupied',
    lockers_floor: 'Floor',
    lockers_status: 'Status',
    lockers_availability: 'Availability',
    lockers_actions: 'Actions',
    lockers_search: 'Search by locker number...',
    lockers_all_floors: 'All Floors',
    lockers_all_sizes: 'All Sizes',
    lockers_all_status: 'All Status',
    lockers_all_avail: 'All Availability',
    lockers_small: 'Small',
    lockers_medium: 'Medium',
    lockers_large: 'Large',
    lockers_active: 'Active',
    lockers_inactive: 'Inactive',
    lockers_available: 'Available',
    lockers_full: 'Full',
    lockers_import_csv: 'Import CSV',
    lockers_loading: 'Loading lockers...',
    lockers_empty: 'No lockers found.',
    lockers_delete_title: 'Delete Locker',
    lockers_delete_msg: 'Are you sure you want to delete locker "{number}"? This action cannot be undone.',
    lockers_delete_bulk_title: 'Delete Lockers',
    lockers_delete_bulk_msg: 'Are you sure you want to delete {count} locker(s)? This action cannot be undone.',
    lockers_delete_selected: 'Delete {count} selected',
    lockers_failed_load: 'Failed to load lockers',
    lockers_failed_delete: 'Failed to delete locker',
    lockers_failed_delete_n: 'Failed to delete {count} locker(s)',
    lockers_op_failed: 'Operation failed',
    lockers_imported: 'Imported: {created} created, {skipped} skipped',
    lockers_csv_failed: 'CSV import failed',

    // Assignments
    assign_title: 'Assignments',
    assign_add: '+ Assign Locker',
    assign_btn: 'Assign',
    assign_form_title: 'Assign Locker to Student',
    assign_student: 'Student',
    assign_student_lc: 'student',
    assign_locker: 'Locker',
    assign_select_student: 'Select a student...',
    assign_select_locker: 'Select a locker...',
    assign_assigned_at: 'Assigned At',
    assign_released_at: 'Released At',
    assign_status: 'Status',
    assign_actions: 'Actions',
    assign_search: 'Search by student or locker...',
    assign_all_status: 'All Status',
    assign_active: 'Active',
    assign_released: 'Assignment released!',
    assign_released_label: 'Released',
    assign_release: 'Release',
    assign_loading: 'Loading assignments...',
    assign_empty: 'No assignments found.',
    assign_success: 'Locker assigned successfully!',
    assign_failed: 'Assignment failed',
    assign_release_failed: 'Release failed',
    assign_release_title: 'Release Assignment',
    assign_release_msg: 'Release locker "{locker}" from "{student}"?',
    assign_failed_load: 'Failed to load data',
    assign_priority_override_title: 'Priority Students Waiting',
    assign_priority_warning: 'There are {count} priority (inclusive) student(s) still without a locker. It is recommended to assign them first. Proceed anyway?',
    assign_assign_anyway: 'Assign Anyway',
    assign_release_all: 'Release All',
    assign_release_all_title: 'Release All Assignments',
    assign_release_all_msg: 'This will release all {count} active assignment(s). All lockers will be freed. This action cannot be undone. Proceed?',
    assign_release_all_confirm: 'Release All',
    assign_release_all_success: 'Successfully released {count} assignment(s).',
    assign_release_all_none: 'No active assignments to release',
    auto_preview: 'Auto Preview',
    auto_apply: 'Apply Auto',
    auto_preview_title: 'Auto Assignment Preview',
    auto_hide: 'Hide',
    auto_empty: 'No students can be auto-assigned right now.',
    auto_preview_failed: 'Auto assignment preview failed',
    auto_apply_title: 'Apply Auto Assignment',
    auto_apply_msg: 'Create {count} automatic assignment(s)?',
    auto_apply_confirm: 'Apply',
    auto_success: 'Auto-assigned {count} student(s).',
    auto_failed: 'Auto assignment failed',
    auto_summary: 'Planned: {planned}, available spots: {spots}, skipped students: {skipped}',
    auto_showing_first: 'Showing first 20 assignments.',
    auto_priority: 'Priority',

    // Users
    users_title: 'Users',
    users_create_title: 'Create User Account',
    users_email: 'Email (university email)',
    users_password: 'Password',
    users_password_ph: 'Set a password',
    users_role: 'Role',
    users_role_user: 'User',
    users_role_admin: 'Admin',
    users_link_student: 'Link to Student',
    users_select_student: 'Select a student',
    users_user: 'User',
    users_admin: 'Admin',
    users_create_btn: 'Create & Send Credentials',
    users_creating: 'Creating...',
    users_student: 'Student',
    users_barcode: 'Barcode',
    users_actions: 'Actions',
    users_search: 'Search by email, student name, barcode...',
    users_empty: 'No users found',
    users_loading: 'Loading users...',
    users_delete_title: 'Delete User',
    users_delete_msg: 'Are you sure you want to delete user "{email}"? This action cannot be undone.',
    users_delete_bulk_title: 'Delete Users',
    users_delete_bulk_msg: 'Are you sure you want to delete {count} user(s)? This action cannot be undone.',
    users_delete_selected: 'Delete {count} selected',
    users_failed_load: 'Failed to load users',
    users_create_failed: 'Failed to create user',
    users_delete_failed: 'Failed to delete user',
    users_failed_delete_n: 'Failed to delete {count} user(s)',
    users_created_email: 'Account created for {email}. Credentials sent via email.',
    users_created_no_email: 'Account created for {email}, but email delivery failed. Please share credentials manually.',
    users_deleted: 'User {email} deleted.',
    users_deleted_n: '{count} user(s) deleted.',

    // User Dashboard
    ud_welcome: 'Welcome back!',
    ud_welcome_name: 'Welcome back, {name}!',
    ud_total: 'Total',
    ud_active: 'Active',
    ud_past: 'Past',
    ud_course: 'course',
    ud_active_locker: 'Your Active Locker',
    ud_your_locker: 'Your Active Locker',
    ud_floor: 'Floor',
    ud_size: 'Size',
    ud_access: 'Access',
    ud_capacity: 'Capacity',
    ud_assigned: 'Assigned',
    ud_duration: 'Duration',
    ud_days: 'days',
    ud_no_locker: 'No Active Locker',
    ud_no_locker_desc: 'You do not have a locker assigned. Contact an administrator.',
    ud_history: 'Assignment History',
    ud_released: 'Released',
    ud_no_profile: 'No Student Profile Linked',
    ud_no_profile_desc: 'Your account is not linked to a student profile. Contact an administrator.',
    ud_no_student: 'No Student Profile Linked',
    ud_no_student_desc: 'Your account is not linked to a student profile. Contact an administrator.',
    ud_loading: 'Loading your dashboard...',
    ud_failed_load: 'Failed to load your dashboard',
    ud_error: 'Failed to load your dashboard',

    // Common
    btn_edit: 'Edit',
    btn_delete: 'Delete',
    btn_cancel: 'Cancel',
    btn_create: 'Create',
    btn_update: 'Update',
    btn_assign: 'Assign',
    btn_clear: 'Clear',
    btn_confirm: 'Confirm',
    results: 'Results',
    of: 'of',
    footer_up: 'Up',

    // Navbar extras
    nav_analytics: 'Analytics',
    nav_management: 'Management',
    nav_maintenance: 'Maintenance',
    nav_activity: 'Activity',
    nav_notifications: 'Notifications',
    nav_change_password: 'Change Password',

    // Maintenance
    lockers_maintenance: 'Maintenance',

    // Analytics
    analytics_loading: 'Loading analytics...',
    analytics_error: 'Failed to load analytics data.',
    analytics_title: 'Analytics',
    analytics_week: 'Week',
    analytics_month: 'Month',
    analytics_quarter: 'Quarter',
    analytics_total_capacity: 'Total Capacity',
    analytics_current_occupied: 'Occupied Now',
    analytics_current_rate: 'Occupancy Rate',
    analytics_maintenance: 'Maintenance',
    analytics_occupancy_trend: 'Occupancy Trend',
    analytics_activity: 'Activity',
    analytics_no_activity: 'No activity in this period.',
    analytics_new_assignments: 'New Assignments',
    analytics_releases: 'Releases',
    analytics_none: 'None',
    analytics_by_size: 'By Size',
    analytics_lockers: 'lockers',
    analytics_peak_days: 'Peak Days',
    analytics_assignments: 'assignments',
    analytics_advanced_title: 'Advanced Analytics',
    analytics_priority_students: 'Priority students',
    analytics_without_locker: 'Without locker',
    analytics_avg_days_used: 'Avg days used',
    analytics_busiest_floors: 'Busiest Floors',
    analytics_popular_sizes: 'Popular Sizes',
    analytics_floor: 'Floor',
    analytics_used_detail: '{occupied}/{capacity} used',
    analytics_size_detail: '{occupied}/{capacity} spots, {lockers} lockers',
    analytics_assignment_count: '{count} assignments',

    // Audit log
    audit_loading: 'Loading activity log...',
    audit_title: 'Activity Log',
    audit_search: 'Search by user, action, entity...',
    audit_date: 'Date',
    audit_user: 'User',
    audit_action: 'Action',
    audit_entity: 'Entity',
    audit_summary: 'Summary',
    audit_system: 'System',
    audit_empty: 'No activity found.',
    audit_action_create: 'Create',
    audit_action_update: 'Update',
    audit_action_delete: 'Delete',
    audit_action_assign: 'Assign',
    audit_action_release: 'Release',
    audit_action_release_all: 'Release All',
    audit_action_auto_assign: 'Auto Assign',
    audit_action_import: 'Import',
    audit_entity_student: 'Student',
    audit_entity_locker: 'Locker',
    audit_entity_assignment: 'Assignment',
    audit_entity_incident: 'Incident',

    // Incidents
    incidents_loading: 'Loading incidents...',
    incidents_failed_load: 'Failed to load incidents',
    incidents_title: 'Incidents & Maintenance',
    incidents_add: '+ Add Incident',
    incidents_edit: 'Edit Incident',
    incidents_new: 'New Incident',
    incidents_delete_title: 'Delete Incident',
    incidents_delete_msg: 'Delete incident "{title}"?',
    incidents_locker: 'Locker',
    incidents_select_locker: 'Select locker...',
    incidents_type: 'Type',
    incidents_status: 'Status',
    incidents_item_title: 'Title',
    incidents_description: 'Description',
    incidents_all_statuses: 'All statuses',
    incidents_created: 'Created',
    incidents_resolved: 'Resolved',
    incidents_actions: 'Actions',
    incidents_empty: 'No incidents found.',
    incidents_operation_failed: 'Operation failed',
    incident_type_broken_door: 'Broken door',
    incident_type_lost_key: 'Lost key',
    incident_type_lock_broken: 'Broken lock',
    incident_type_needs_repair: 'Needs repair',
    incident_type_other: 'Other',
    incident_status_open: 'Open',
    incident_status_in_progress: 'In progress',
    incident_status_resolved: 'Resolved',
    incident_status_cancelled: 'Cancelled',

    // Notifications
    notifications_loading: 'Loading notifications...',
    notifications_title: 'Notifications',
    notifications_mark_all_read: 'Mark all read',
    notifications_read: 'Read',
    notifications_empty: 'No notifications yet.',
    notifications_locker_assigned_title: 'Locker assigned',
    notifications_locker_released_title: 'Locker released',
    notifications_incident_created_title: 'Incident created',
    notifications_locker_assigned_msg: 'Locker {locker} on floor {floor} has been assigned to you.',
    notifications_locker_released_msg: 'Locker {locker} has been released.',
    notifications_incident_created_msg: 'Locker {locker} moved to maintenance: {title}',

    // Password change
    pwd_title: 'Change Password',
    pwd_current: 'Current Password',
    pwd_new: 'New Password',
    pwd_confirm: 'Confirm New Password',
    pwd_save: 'Change Password',
    pwd_saving: 'Saving...',
    pwd_success: 'Password changed successfully!',
    pwd_failed: 'Failed to change password.',
    pwd_mismatch: 'New passwords do not match.',
    pwd_min_length: 'Password must be at least 6 characters.',
    pwd_show: 'Show password',
    pwd_hide: 'Hide password',

    // Combined CSV import
    csv_combined_import: 'Import Combined CSV',
    csv_combined_failed: 'Combined CSV import failed',
    csv_combined_result: 'Import complete: {students} students, {lockers} lockers, {assignments} assignments created, {skipped} skipped',

    // Welcome page
    welcome_login_btn: 'Sign In',
    welcome_hero_badge: 'AITU Locker',
    welcome_hero_title: 'Smart Locker Management for Students',
    welcome_hero_subtitle: 'Easily assign, track, and manage lockers across all floors of Astana IT University. Built for admins and students alike.',
    welcome_get_started: 'Get Started',
    welcome_learn_more: 'Learn More',
    welcome_stat_lockers: 'Lockers',
    welcome_stat_students: 'Students',
    welcome_stat_floors: 'Floors',
    welcome_stat_uptime: 'Uptime',
    welcome_features_title: 'Everything You Need',
    welcome_features_subtitle: 'A complete toolset for efficient campus locker management.',
    welcome_feat1_title: 'Locker Inventory',
    welcome_feat1_desc: 'Manage hundreds of lockers across floors with real-time occupancy tracking.',
    welcome_feat2_title: 'Student Management',
    welcome_feat2_desc: 'Link students to user accounts and bulk-import records via CSV.',
    welcome_feat3_title: 'Live Dashboard',
    welcome_feat3_desc: 'Real-time stats on occupancy, floor breakdowns, and assignment trends.',
    welcome_feat4_title: 'Secure Access',
    welcome_feat4_desc: 'JWT-based authentication with role separation between admins and students.',
    welcome_feat5_title: 'PIN & Key Support',
    welcome_feat5_desc: 'Supports both PIN-code and physical-key locker types with automatic capacity rules.',
    welcome_feat6_title: 'Multi-Floor',
    welcome_feat6_desc: 'Organize lockers by floor and filter by size, type, or availability.',
    welcome_feat7_title: 'Email Notifications',
    welcome_feat7_desc: 'Automated emails on account creation, locker assignment, and release.',
    welcome_feat8_title: 'CSV Import / Export',
    welcome_feat8_desc: 'Bulk-import students and lockers from spreadsheets in seconds.',
    welcome_gallery_title: 'Our System',
    welcome_gallery_subtitle: 'Designed for Astana IT University campus.',
    welcome_gallery1: 'Astana IT University',
    welcome_gallery2: 'Locker Management System',
    welcome_gallery3: 'Secure Campus Lockers',
    welcome_how_title: 'How It Works',
    welcome_step1_title: 'Admin Creates Account',
    welcome_step1_desc: 'Administrator adds a student record and creates a user login. Credentials are emailed automatically.',
    welcome_step2_title: 'Locker Is Assigned',
    welcome_step2_desc: 'Admin picks a free locker and assigns it to the student in one click.',
    welcome_step3_title: 'Student Logs In',
    welcome_step3_desc: 'Student signs in and sees their active locker, floor, and assignment history.',
    welcome_step4_title: 'Locker Is Released',
    welcome_step4_desc: 'When no longer needed, admin releases the locker so it becomes available again.',
    welcome_cta_title: 'Ready to get started?',
    welcome_cta_subtitle: 'Sign in to access the locker management dashboard.',
    welcome_footer_rights: 'All rights reserved.',

    // 404 Not Found
    nf_badge: '404 Error',
    nf_title: 'Locker Compartment Not Found',
    nf_subtitle: 'The page or locker section you are trying to access does not exist, has been moved, or is temporarily unavailable.',
    nf_btn_home: 'Dashboard',
    nf_btn_welcome: 'Back to Home',
    nf_btn_back: 'Go Back',
    nf_quick_links: 'Helpful Shortcuts:',
    nf_link_lockers: 'Lockers',
    nf_link_students: 'Students',
    nf_link_incidents: 'Incidents',
    nf_link_mylocker: 'My Locker',
    nf_link_login: 'Login',

    // Technician & AI Auto-Assign additions
    nav_technician_tasks: 'Technician Tasks',
    nav_tech_workspace: 'Tech Workspace',
    users_role_technician: 'Technician',
    users_technician: 'Technician',

    // AI Smart Allocation
    ai_auto_title: 'Smart AI Locker Allocation',
    ai_auto_desc: 'Automated intelligent locker matching based on priority status, GPA performance, usage activity, and accessible floor routing.',
    ai_page_subtitle: 'View, create, and manage active student locker assignments across the campus.',
    ai_run_btn: 'Run AI Allocation',
    ai_running_btn: 'Calculating allocations...',
    ai_step_1_title: 'Priority Categories',
    ai_step_1_desc: 'Inclusive and priority students are allocated to accessible ground floor lockers.',
    ai_step_2_title: 'High Activity',
    ai_step_2_desc: 'Frequent system users receive early queue priority.',
    ai_step_3_title: 'Academic Excellence (GPA)',
    ai_step_3_desc: 'High GPA students matched to optimal lockers next.',
    ai_step_4_title: 'General Stream',
    ai_step_4_desc: 'Remaining student body allocated to available lockers.',
    ai_custom_rules_label: 'Additional AI Guidelines (Optional):',
    ai_custom_rules_placeholder: 'e.g. «prioritize group SE-2204 on Floor 2» or «give preference to 1st year students»',
    ai_calc_title: 'AI Smart Allocation in progress...',
    ai_calc_step_1: '1. Filtering inclusive & accessibility cohorts (Floor 1)',
    ai_calc_step_2: '2. Ranking high-activity & loyalty student accounts',
    ai_calc_step_3: '3. Matching academic excellence (GPA >= 3.4)',
    ai_calc_step_4: '4. Optimizing general cohorts across campus floors',
    ai_sim_title: 'Smart AI Allocation Simulation',
    ai_sim_commit_btn: 'Commit Assignments ({count})',
    ai_sim_hide_btn: 'Hide',
    ai_sim_summary_text: 'Simulation result: {planned} planned, {spots} available spots, {skipped} skipped.',
    ai_already_all_assigned: 'All students are already assigned to lockers.',
    ai_api_key_missing: 'AI Engine API key is not configured. Please set GEMINI_API_KEY in the root .env file.',
    ai_commit_confirm_title: 'Apply Locker Allocations?',
    ai_commit_confirm_msg: 'Confirm creating {count} locker assignments generated by Smart AI?',
    ai_commit_btn_text: 'Apply',
    ai_commit_success_msg: 'AI allocation completed successfully: created {count} assignments.',
    ai_tier_1: 'Tier 1: Inclusive & Priority',
    ai_tier_2: 'Tier 2: Active Users',
    ai_tier_3: 'Tier 3: Academic Excellence (GPA)',
    ai_tier_4: 'Tier 4: General Student Body',
    ai_tier_1_badge: 'Priority',
    ai_tier_2_badge: 'Active',
    ai_tier_3_badge: 'High GPA',
    ai_tier_4_badge: 'General',
    ai_preview_btn: 'AI Auto-Assign',
    ai_reason_header: 'AI Allocation Justification',
    ai_apply_btn: 'Commit AI Allocations',
    ai_simulation_summary: 'AI Matching Simulation: {planned} students matched into {spots} available spots ({skipped} skipped).',
    ai_tier_stats: 'Tier Breakdown: T1 (Inclusive): {t1} | T2 (Active): {t2} | T3 (GPA): {t3} | T4 (General): {t4}',
    assign_col_priority: 'Priority',
    assign_col_metrics: 'Metrics',
    assign_showing_first_n: 'Showing first {count} of {total} assignments.',

    // Technician & Incident reporting
    incident_report_defect: 'Report Locker Defect',
    incident_report_title: 'Report a Locker Defect',
    incident_report_desc: 'Describe the issue and attach a photo to dispatch maintenance technician.',
    incident_attach_photo: 'Attach Photo of Defect',
    incident_photo_preview: 'Defect Photo Preview',
    incident_photo_remove: 'Remove Photo',
    incident_photo_click_zoom: 'Click to enlarge photo',
    incident_assigned_to: 'Assigned Technician',
    incident_assign_btn: 'Assign Technician',
    incident_assign_modal_title: 'Assign Task to Technician',
    incident_select_tech: 'Select a technician...',
    incident_no_techs: 'No technician accounts available. Create one in Users page.',
    incident_status_assigned: 'Assigned to Tech',
    incident_start_repair: 'Start Repair',
    incident_resolve_repair: 'Complete & Mark Fixed',
    incident_resolve_modal_title: 'Complete Repair Report',
    incident_notes_placeholder: 'Describe the repair work performed, replaced parts, or lock reset details...',
    incident_tech_notes: 'Technician Report / Notes',
    incident_reporter: 'Reported By',
    incident_my_tasks: 'My Assigned Tasks',
    incident_reported_success: 'Defect report submitted successfully. Admin and technician have been notified!',
    tech_dashboard_title: 'Technician Workspace',
    tech_dashboard_subtitle: 'Manage and resolve reported locker defects and maintenance tasks',
    tech_assigned_tasks: 'Assigned to Me',
    tech_in_progress: 'In Progress',
    tech_resolved_today: 'Completed / Fixed',
    tech_no_tasks: 'No tasks assigned currently. Great job!',
    tech_task_card_floor: 'Floor',
    tech_view_photo: 'View Defect Photo',
    tech_mark_progress_success: 'Task marked as In Progress.',
    tech_resolve_success: 'Locker repaired! Student and admin notified.',
    ud_report_issue: 'Report Issue / Defect',
    ud_my_reports: 'My Maintenance Reports',
    ud_no_reports: 'No open repair tickets for your locker.',
  },

  ru: {
    // Navbar
    nav_brand: 'AITU Locker',
    nav_dashboard: 'Главная',
    nav_users: 'Пользователи',
    nav_students: 'Студенты',
    nav_lockers: 'Шкафчики',
    nav_assignments: 'Назначения',
    nav_my_locker: 'Мой шкафчик',
    nav_logout: 'Выйти',
    nav_theme_dark: 'Тёмная тема',
    nav_theme_light: 'Светлая тема',

    // Login
    login_placeholder_email: 'Логин',
    login_placeholder_password: 'Пароль',
    login_btn: 'Вход',
    login_loading: 'Вход...',
    login_failed: 'Ошибка входа',

    // Dashboard
    dash_title: 'Главная',
    dash_subtitle: 'Обзор системы управления шкафчиками в реальном времени',
    dash_total_capacity: 'Общая вместимость',
    dash_occupied: 'Занято',
    dash_available: 'Свободно',
    dash_occupied_pct: 'Занято',
    dash_used: 'Занято',
    dash_free: 'Свободно',
    dash_students: 'Студенты',
    dash_lockers: 'Шкафчики',
    dash_assignments: 'Назначения',
    dash_users: 'Пользователи',
    dash_recent: 'Последние назначения',
    dash_view_all: 'Все →',
    dash_no_assignments: 'Назначений пока нет',
    dash_occupancy_floor: 'Занятость по этажам',
    dash_view_lockers: 'К шкафчикам →',
    dash_no_lockers: 'Нет активных шкафчиков',
    dash_floor: 'Этаж',
    dash_lockers_unit: 'шкафч.',
    dash_used_unit: 'занято',
    dash_students_by_course: 'Студенты по курсам',
    dash_course: 'Курс',
    dash_students_unit: 'студ.',
    dash_loading: 'Загрузка панели...',
    dash_error: 'Не удалось загрузить данные.',
    dash_locker: 'Шкафчик',
    dash_active: 'Активно',
    dash_released: 'Освобождён',
    dash_just_now: 'Только что',
    dash_m_ago: 'мин назад',
    dash_h_ago: 'ч назад',
    dash_d_ago: 'дн назад',

    // Students
    students_title: 'Управление студентами',
    students_add: '+ Добавить студента',
    students_edit: 'Редактировать студента',
    students_add_new: 'Добавить нового студента',
    students_full_name: 'ФИО',
    students_group: 'Группа',
    students_barcode: 'Штрихкод',
    students_course: 'Курс',
    students_actions: 'Действия',
    students_search: 'Поиск по имени, группе, штрихкоду...',
    students_all_groups: 'Все группы',
    students_all_courses: 'Все курсы',
    students_all_statuses: 'Все статусы',
    students_inclusive_status: 'Статус льготника',
    inclusive_none: 'Без особого статуса',
    inclusive_disability: 'Инвалидность',
    inclusive_orphan: 'Сирота',
    inclusive_vision: 'Нарушение зрения',
    inclusive_hearing: 'Нарушение слуха',
    inclusive_other: 'Иное',
    inclusive_filter_priority: 'Приоритетные студенты',
    students_course_unit: 'курс',
    students_import_csv: 'Импорт CSV',
    students_loading: 'Загрузка студентов...',
    students_empty: 'Студенты не найдены.',
    students_delete_title: 'Удалить студента',
    students_delete_msg: 'Вы уверены, что хотите удалить "{name}"? Это действие необратимо.',
    students_delete_bulk_title: 'Удалить студентов',
    students_delete_bulk_msg: 'Вы уверены, что хотите удалить {count} студент(ов)? Это действие необратимо.',
    students_delete_selected: 'Удалить {count} выбр.',
    students_failed_load: 'Не удалось загрузить студентов',
    students_failed_delete: 'Не удалось удалить студента',
    students_failed_delete_n: 'Не удалось удалить {count} студент(ов)',
    students_op_failed: 'Операция не удалась',
    students_imported: 'Импорт: {created} создано, {skipped} пропущено',
    students_csv_failed: 'Импорт CSV не удался',

    // Lockers
    lockers_title: 'AITU Locker',
    lockers_add: '+ Добавить шкафчик',
    lockers_edit: 'Редактировать шкафчик',
    lockers_add_new: 'Добавить новый шкафчик',
    lockers_number: 'Номер',
    lockers_size: 'Размер',
    lockers_access: 'Доступ',
    lockers_capacity: 'Вместимость',
    lockers_capacity_auto: 'Вместимость (авто)',
    lockers_occupied: 'Занято',
    lockers_floor: 'Этаж',
    lockers_status: 'Статус',
    lockers_availability: 'Доступность',
    lockers_actions: 'Действия',
    lockers_search: 'Поиск по номеру шкафчика...',
    lockers_all_floors: 'Все этажи',
    lockers_all_sizes: 'Все размеры',
    lockers_all_status: 'Все статусы',
    lockers_all_avail: 'Вся доступность',
    lockers_small: 'Маленький',
    lockers_medium: 'Средний',
    lockers_large: 'Большой',
    lockers_active: 'Активный',
    lockers_inactive: 'Неактивный',
    lockers_available: 'Свободен',
    lockers_full: 'Занят',
    lockers_import_csv: 'Импорт CSV',
    lockers_loading: 'Загрузка шкафчиков...',
    lockers_empty: 'Шкафчики не найдены.',
    lockers_delete_title: 'Удалить шкафчик',
    lockers_delete_msg: 'Вы уверены, что хотите удалить шкафчик "{number}"? Это действие необратимо.',
    lockers_delete_bulk_title: 'Удалить шкафчики',
    lockers_delete_bulk_msg: 'Вы уверены, что хотите удалить {count} шкафчик(ов)? Это действие необратимо.',
    lockers_delete_selected: 'Удалить {count} выбр.',
    lockers_failed_load: 'Не удалось загрузить шкафчики',
    lockers_failed_delete: 'Не удалось удалить шкафчик',
    lockers_failed_delete_n: 'Не удалось удалить {count} шкафчик(ов)',
    lockers_op_failed: 'Операция не удалась',
    lockers_imported: 'Импорт: {created} создано, {skipped} пропущено',
    lockers_csv_failed: 'Импорт CSV не удался',

    // Assignments
    assign_title: 'Назначения',
    assign_add: '+ Назначить шкафчик',
    assign_btn: 'Назначить',
    assign_form_title: 'Назначить шкафчик студенту',
    assign_student: 'Студент',
    assign_student_lc: 'студент',
    assign_locker: 'Шкафчик',
    assign_select_student: 'Выберите студента...',
    assign_select_locker: 'Выберите шкафчик...',
    assign_assigned_at: 'Назначено',
    assign_released_at: 'Освобождено',
    assign_status: 'Статус',
    assign_actions: 'Действия',
    assign_search: 'Поиск по студенту или шкафчику...',
    assign_all_status: 'Все статусы',
    assign_active: 'Активно',
    assign_released: 'Назначение освобождено!',
    assign_released_label: 'Освобождён',
    assign_release: 'Освободить',
    assign_loading: 'Загрузка назначений...',
    assign_empty: 'Назначения не найдены.',
    assign_success: 'Шкафчик успешно назначен!',
    assign_failed: 'Ошибка назначения',
    assign_release_failed: 'Ошибка освобождения',
    assign_release_title: 'Освободить назначение',
    assign_release_msg: 'Освободить шкафчик "{locker}" от "{student}"?',
    assign_failed_load: 'Не удалось загрузить данные',
    assign_priority_override_title: 'Ожидают приоритетные студенты',
    assign_priority_warning: 'Есть {count} льготных студент(ов), у которых ещё нет шкафчика. Рекомендуется назначить их первыми. Всё равно продолжить?',
    assign_assign_anyway: 'Назначить всё равно',
    assign_release_all: 'Освободить все',
    assign_release_all_title: 'Освободить все назначения',
    assign_release_all_msg: 'Это освободит все {count} активных назначений. Все шкафчики будут свободны. Действие нельзя отменить. Продолжить?',
    assign_release_all_confirm: 'Освободить все',
    assign_release_all_success: 'Успешно освобождено назначений: {count}.',
    assign_release_all_none: 'Нет активных назначений для освобождения',
    auto_preview: 'Авто-предпросмотр',
    auto_apply: 'Применить авто',
    auto_preview_title: 'Предпросмотр автораспределения',
    auto_hide: 'Скрыть',
    auto_empty: 'Сейчас нет студентов для автораспределения.',
    auto_preview_failed: 'Не удалось подготовить автораспределение',
    auto_apply_title: 'Применить автораспределение',
    auto_apply_msg: 'Создать автоматические назначения: {count}?',
    auto_apply_confirm: 'Применить',
    auto_success: 'Автоматически назначено студентов: {count}.',
    auto_failed: 'Ошибка автораспределения',
    auto_summary: 'Запланировано: {planned}, свободных мест: {spots}, пропущено студентов: {skipped}',
    auto_showing_first: 'Показаны первые 20 назначений.',
    auto_priority: 'Приоритет',

    // Users
    users_title: 'Пользователи',
    users_create_title: 'Создать аккаунт',
    users_email: 'Email (университетская почта)',
    users_password: 'Пароль',
    users_password_ph: 'Задайте пароль',
    users_role: 'Роль',
    users_role_user: 'Пользователь',
    users_role_admin: 'Администратор',
    users_link_student: 'Привязать к студенту',
    users_select_student: 'Выберите студента',
    users_user: 'Пользователь',
    users_admin: 'Администратор',
    users_create_btn: 'Создать и отправить данные',
    users_creating: 'Создание...',
    users_student: 'Студент',
    users_barcode: 'Штрихкод',
    users_actions: 'Действия',
    users_search: 'Поиск по email, имени студента, штрихкоду...',
    users_empty: 'Пользователи не найдены',
    users_loading: 'Загрузка пользователей...',
    users_delete_title: 'Удалить пользователя',
    users_delete_msg: 'Вы уверены, что хотите удалить пользователя "{email}"? Это действие необратимо.',
    users_delete_bulk_title: 'Удалить пользователей',
    users_delete_bulk_msg: 'Вы уверены, что хотите удалить {count} пользователей? Это действие необратимо.',
    users_delete_selected: 'Удалить {count} выбр.',
    users_failed_load: 'Не удалось загрузить пользователей',
    users_create_failed: 'Не удалось создать пользователя',
    users_delete_failed: 'Не удалось удалить пользователя',
    users_failed_delete_n: 'Не удалось удалить {count} пользователей',
    users_created_email: 'Аккаунт создан для {email}. Данные отправлены на email.',
    users_created_no_email: 'Аккаунт создан для {email}, но письмо не доставлено. Передайте данные вручную.',
    users_deleted: 'Пользователь {email} удалён.',
    users_deleted_n: '{count} пользователь(ей) удалено.',

    // User Dashboard
    ud_welcome: 'С возвращением!',
    ud_welcome_name: 'С возвращением, {name}!',
    ud_total: 'Всего',
    ud_active: 'Активно',
    ud_past: 'Прошлые',
    ud_course: 'курс',
    ud_active_locker: 'Ваш активный шкафчик',
    ud_your_locker: 'Ваш активный шкафчик',
    ud_floor: 'Этаж',
    ud_size: 'Размер',
    ud_access: 'Доступ',
    ud_capacity: 'Вместимость',
    ud_assigned: 'Назначен',
    ud_duration: 'Длительность',
    ud_days: 'дней',
    ud_no_locker: 'Нет активного шкафчика',
    ud_no_locker_desc: 'У вас нет назначенного шкафчика. Обратитесь к администратору.',
    ud_history: 'История назначений',
    ud_released: 'Освобождён',
    ud_no_profile: 'Профиль студента не привязан',
    ud_no_profile_desc: 'Ваш аккаунт не привязан к профилю студента. Обратитесь к администратору.',
    ud_no_student: 'Профиль студента не привязан',
    ud_no_student_desc: 'Ваш аккаунт не привязан к профилю студента. Обратитесь к администратору.',
    ud_loading: 'Загрузка панели...',
    ud_failed_load: 'Не удалось загрузить панель',
    ud_error: 'Не удалось загрузить панель',

    // Common
    btn_edit: 'Редакт.',
    btn_delete: 'Удалить',
    btn_cancel: 'Отмена',
    btn_create: 'Создать',
    btn_update: 'Обновить',
    btn_assign: 'Назначить',
    btn_clear: 'Очистить',
    btn_confirm: 'Подтвердить',
    results: 'Результаты',
    of: 'из',
    footer_up: 'Наверх',

    // Navbar extras
    nav_analytics: 'Аналитика',
    nav_management: 'Управление',
    nav_maintenance: 'Обслуживание',
    nav_activity: 'Журнал',
    nav_notifications: 'Уведомления',
    nav_change_password: 'Сменить пароль',

    // Maintenance
    lockers_maintenance: 'На обслуживании',

    // Analytics
    analytics_loading: 'Загрузка аналитики...',
    analytics_error: 'Не удалось загрузить аналитику.',
    analytics_title: 'Аналитика',
    analytics_week: 'Неделя',
    analytics_month: 'Месяц',
    analytics_quarter: 'Квартал',
    analytics_total_capacity: 'Общая вместимость',
    analytics_current_occupied: 'Занято сейчас',
    analytics_current_rate: 'Загруженность',
    analytics_maintenance: 'На обслуживании',
    analytics_occupancy_trend: 'Тренд занятости',
    analytics_activity: 'Активность',
    analytics_no_activity: 'Нет активности за этот период.',
    analytics_new_assignments: 'Новые назначения',
    analytics_releases: 'Освобождения',
    analytics_none: 'Нет',
    analytics_by_size: 'По размеру',
    analytics_lockers: 'шкафчиков',
    analytics_peak_days: 'Самые загруженные дни',
    analytics_assignments: 'назначений',
    analytics_advanced_title: 'Расширенная аналитика',
    analytics_priority_students: 'Приоритетные студенты',
    analytics_without_locker: 'Без шкафчика',
    analytics_avg_days_used: 'Среднее число дней',
    analytics_busiest_floors: 'Самые загруженные этажи',
    analytics_popular_sizes: 'Популярные размеры',
    analytics_floor: 'Этаж',
    analytics_used_detail: '{occupied}/{capacity} занято',
    analytics_size_detail: '{occupied}/{capacity} мест, шкафчиков: {lockers}',
    analytics_assignment_count: 'Назначений: {count}',

    // Audit log
    audit_loading: 'Загрузка журнала действий...',
    audit_title: 'Журнал действий',
    audit_search: 'Поиск по пользователю, действию, сущности...',
    audit_date: 'Дата',
    audit_user: 'Пользователь',
    audit_action: 'Действие',
    audit_entity: 'Сущность',
    audit_summary: 'Описание',
    audit_system: 'Система',
    audit_empty: 'Действия не найдены.',
    audit_action_create: 'Создание',
    audit_action_update: 'Изменение',
    audit_action_delete: 'Удаление',
    audit_action_assign: 'Назначение',
    audit_action_release: 'Освобождение',
    audit_action_release_all: 'Освобождение всех',
    audit_action_auto_assign: 'Автораспределение',
    audit_action_import: 'Импорт',
    audit_entity_student: 'Студент',
    audit_entity_locker: 'Шкафчик',
    audit_entity_assignment: 'Назначение',
    audit_entity_incident: 'Инцидент',

    // Incidents
    incidents_loading: 'Загрузка инцидентов...',
    incidents_failed_load: 'Не удалось загрузить инциденты',
    incidents_title: 'Инциденты и ремонт',
    incidents_add: '+ Добавить инцидент',
    incidents_edit: 'Редактировать инцидент',
    incidents_new: 'Новый инцидент',
    incidents_delete_title: 'Удалить инцидент',
    incidents_delete_msg: 'Удалить инцидент "{title}"?',
    incidents_locker: 'Шкафчик',
    incidents_select_locker: 'Выберите шкафчик...',
    incidents_type: 'Тип',
    incidents_status: 'Статус',
    incidents_item_title: 'Заголовок',
    incidents_description: 'Описание',
    incidents_all_statuses: 'Все статусы',
    incidents_created: 'Создан',
    incidents_resolved: 'Решён',
    incidents_actions: 'Действия',
    incidents_empty: 'Инциденты не найдены.',
    incidents_operation_failed: 'Операция не выполнена',
    incident_type_broken_door: 'Сломана дверь',
    incident_type_lost_key: 'Потерян ключ',
    incident_type_lock_broken: 'Сломался замок',
    incident_type_needs_repair: 'Требуется ремонт',
    incident_type_other: 'Другое',
    incident_status_open: 'Открыт',
    incident_status_in_progress: 'В работе',
    incident_status_resolved: 'Решён',
    incident_status_cancelled: 'Отменён',

    // Notifications
    notifications_loading: 'Загрузка уведомлений...',
    notifications_title: 'Уведомления',
    notifications_mark_all_read: 'Отметить все прочитанными',
    notifications_read: 'Прочитано',
    notifications_empty: 'Уведомлений пока нет.',
    notifications_locker_assigned_title: 'Шкафчик назначен',
    notifications_locker_released_title: 'Шкафчик освобождён',
    notifications_incident_created_title: 'Создан инцидент',
    notifications_locker_assigned_msg: 'Вам назначен шкафчик {locker} на этаже {floor}.',
    notifications_locker_released_msg: 'Шкафчик {locker} был освобождён.',
    notifications_incident_created_msg: 'Шкафчик {locker} переведён на обслуживание: {title}',

    // Password change
    pwd_title: 'Смена пароля',
    pwd_current: 'Текущий пароль',
    pwd_new: 'Новый пароль',
    pwd_confirm: 'Подтвердите новый пароль',
    pwd_save: 'Сменить пароль',
    pwd_saving: 'Сохранение...',
    pwd_success: 'Пароль успешно изменён!',
    pwd_failed: 'Не удалось сменить пароль.',
    pwd_mismatch: 'Новые пароли не совпадают.',
    pwd_min_length: 'Пароль должен быть не менее 6 символов.',
    pwd_show: 'Показать пароль',
    pwd_hide: 'Скрыть пароль',

    // Combined CSV import
    csv_combined_import: 'Импорт общего CSV',
    csv_combined_failed: 'Ошибка импорта CSV',
    csv_combined_result: 'Импорт завершён: {students} студентов, {lockers} шкафчиков, {assignments} назначений создано, {skipped} пропущено',

    // Welcome page
    welcome_login_btn: 'Войти',
    welcome_hero_badge: 'Система управления шкафчиками AITU',
    welcome_hero_title: 'Умное управление шкафчиками для студентов',
    welcome_hero_subtitle: 'Назначайте, отслеживайте и управляйте шкафчиками на всех этажах Astana IT University. Создано для администраторов и студентов.',
    welcome_get_started: 'Начать',
    welcome_learn_more: 'Узнать больше',
    welcome_stat_lockers: 'Шкафчиков',
    welcome_stat_students: 'Студентов',
    welcome_stat_floors: 'Этажей',
    welcome_stat_uptime: 'Доступность',
    welcome_features_title: 'Всё необходимое',
    welcome_features_subtitle: 'Полный набор инструментов для управления шкафчиками кампуса.',
    welcome_feat1_title: 'Инвентарь шкафчиков',
    welcome_feat1_desc: 'Управляйте сотнями шкафчиков на этажах с отслеживанием занятости в реальном времени.',
    welcome_feat2_title: 'Управление студентами',
    welcome_feat2_desc: 'Привязывайте студентов к аккаунтам и импортируйте записи через CSV.',
    welcome_feat3_title: 'Онлайн-панель',
    welcome_feat3_desc: 'Статистика занятости, разбивка по этажам и тренды назначений в реальном времени.',
    welcome_feat4_title: 'Безопасный доступ',
    welcome_feat4_desc: 'JWT-аутентификация с разделением ролей между администраторами и студентами.',
    welcome_feat5_title: 'PIN и ключ',
    welcome_feat5_desc: 'Поддержка PIN-кода и физического ключа с автоматическими правилами вместимости.',
    welcome_feat6_title: 'Несколько этажей',
    welcome_feat6_desc: 'Организация шкафчиков по этажам с фильтрацией по размеру, типу и доступности.',
    welcome_feat7_title: 'Email-уведомления',
    welcome_feat7_desc: 'Автоматические письма при создании аккаунта, назначении и освобождении шкафчика.',
    welcome_feat8_title: 'Импорт и экспорт CSV',
    welcome_feat8_desc: 'Массовый импорт студентов и шкафчиков из таблиц за считанные секунды.',
    welcome_gallery_title: 'Наша система',
    welcome_gallery_subtitle: 'Разработана для кампуса Astana IT University.',
    welcome_gallery1: 'Astana IT University',
    welcome_gallery2: 'Система управления шкафчиками',
    welcome_gallery3: 'Безопасные шкафчики кампуса',
    welcome_how_title: 'Как это работает',
    welcome_step1_title: 'Администратор создаёт аккаунт',
    welcome_step1_desc: 'Администратор добавляет студента и создаёт логин. Данные для входа отправляются на email автоматически.',
    welcome_step2_title: 'Назначение шкафчика',
    welcome_step2_desc: 'Администратор выбирает свободный шкафчик и назначает его студенту в один клик.',
    welcome_step3_title: 'Студент входит',
    welcome_step3_desc: 'Студент входит в систему и видит активный шкафчик, этаж и историю назначений.',
    welcome_step4_title: 'Освобождение шкафчика',
    welcome_step4_desc: 'Когда шкафчик больше не нужен, администратор освобождает его — и он снова становится доступным.',
    welcome_cta_title: 'Готовы начать?',
    welcome_cta_subtitle: 'Войдите, чтобы получить доступ к панели управления шкафчиками.',
    welcome_footer_rights: 'Все права защищены.',

    // 404 Not Found
    nf_badge: 'Ошибка 404',
    nf_title: 'Шкафчик или страница не найдены',
    nf_subtitle: 'Запрашиваемая страница или ячейка не существует, была перемещена или временно недоступна.',
    nf_btn_home: 'В панель управления',
    nf_btn_welcome: 'На главную',
    nf_btn_back: 'Назад',
    nf_quick_links: 'Полезные разделы:',
    nf_link_lockers: 'Шкафчики',
    nf_link_students: 'Студенты',
    nf_link_incidents: 'Обслуживание',
    nf_link_mylocker: 'Мой шкафчик',
    nf_link_login: 'Войти',

    // Дополнения: Техник и ИИ-автораспределение
    nav_technician_tasks: 'Задачи техника',
    nav_tech_workspace: 'Кабинет техника',
    users_role_technician: 'Техник',
    users_technician: 'Техник',

    // ИИ-автораспределение
    ai_auto_title: 'Умное распределение локеров ИИ',
    ai_auto_desc: 'Автоматическое распределение шкафчиков на основе академического приоритета, успеваемости (GPA), уровня активности и медицинских льгот.',
    ai_page_subtitle: 'Просмотр, создание и управление активными назначениями шкафчиков студентам кампуса.',
    ai_run_btn: 'Запустить ИИ-распределение',
    ai_running_btn: 'Выполняется расчет...',
    ai_step_1_title: 'Приоритетная категория',
    ai_step_1_desc: 'Льготные категории гарантированно распределяются на первый (доступный) этаж.',
    ai_step_2_title: 'Высокая активность',
    ai_step_2_desc: 'Студенты с высоким рейтингом использования локеров получают приоритетный доступ.',
    ai_step_3_title: 'Успеваемость (GPA)',
    ai_step_3_desc: 'Отличники и студенты с высоким средним баллом распределяются в следующую очередь.',
    ai_step_4_title: 'Общий поток',
    ai_step_4_desc: 'Остальные незанятые студенты распределяются по оставшимся свободным локерам.',
    ai_custom_rules_label: 'Дополнительные инструкции для ИИ (необязательно):',
    ai_custom_rules_placeholder: 'Например: «приоритетно распределить группу SE-2204 на 2 этаж» или «выделить локеры только для первого курса»',
    ai_calc_title: 'ИИ выполняет расчет распределения локеров...',
    ai_calc_step_1: '1. Анализ льготных и инклюзивных категорий (1 этаж)',
    ai_calc_step_2: '2. Ранжирование по рейтингу активности пользователей',
    ai_calc_step_3: '3. Подбор мест для отличников (GPA >= 3.4)',
    ai_calc_step_4: '4. Оптимизация распределения общего потока студентов',
    ai_sim_title: 'Результаты симуляции распределения ИИ',
    ai_sim_commit_btn: 'Применить назначение ({count})',
    ai_sim_hide_btn: 'Скрыть',
    ai_sim_summary_text: 'Симуляция распределения: запланировано {planned} назначений, свободно {spots} мест, пропущено {skipped} студентов.',
    ai_already_all_assigned: 'ИИ: все студенты уже успешно распределены по ячейкам.',
    ai_api_key_missing: 'API-ключ системы ИИ не настроен. Пожалуйста, укажите GEMINI_API_KEY в файле .env.',
    ai_commit_confirm_title: 'Применить распределение локеров?',
    ai_commit_confirm_msg: 'Подтвердить создание {count} назначений локеров, подобранных системой ИИ?',
    ai_commit_btn_text: 'Применить',
    ai_commit_success_msg: 'ИИ-распределение успешно завершено: создано {count} назначений.',
    ai_tier_1: 'Уровень 1: Льготные категории',
    ai_tier_2: 'Уровень 2: Активные пользователи',
    ai_tier_3: 'Уровень 3: Высокая успеваемость (GPA)',
    ai_tier_4: 'Уровень 4: Общий поток',
    ai_tier_1_badge: 'Льгота',
    ai_tier_2_badge: 'Активный',
    ai_tier_3_badge: 'Отличник',
    ai_tier_4_badge: 'Общий',
    ai_preview_btn: 'ИИ-распределение',
    ai_reason_header: 'Обоснование выбора ИИ',
    ai_apply_btn: 'Подтвердить и распределить',
    ai_simulation_summary: 'Симуляция ИИ: запланировано {planned} назначений на {spots} свободных мест ({skipped} пропущено).',
    ai_tier_stats: 'Распределение по уровням: У1 (Льготы): {t1} | У2 (Активные): {t2} | У3 (GPA): {t3} | У4 (Общий): {t4}',
    assign_col_priority: 'Приоритет',
    assign_col_metrics: 'Метрики',
    assign_showing_first_n: 'Показаны первые {count} из {total} назначений.',

    // Техник и заявки на ремонт
    incident_report_defect: 'Сообщить о неисправности',
    incident_report_title: 'Заявка на ремонт локера',
    incident_report_desc: 'Опишите проблему и прикрепите фото неисправности для отправки технику.',
    incident_attach_photo: 'Прикрепить фото неисправности',
    incident_photo_preview: 'Предпросмотр фото',
    incident_photo_remove: 'Удалить фото',
    incident_photo_click_zoom: 'Нажмите для увеличения',
    incident_assigned_to: 'Назначенный техник',
    incident_assign_btn: 'Назначить технику',
    incident_assign_modal_title: 'Назначить задачу технику',
    incident_select_tech: 'Выберите техника...',
    incident_no_techs: 'Нет учетных записей техников. Создайте их в разделе Пользователи.',
    incident_status_assigned: 'Передана технику',
    incident_start_repair: 'Взять в работу',
    incident_resolve_repair: 'Завершить ремонт / Отремонтировано',
    incident_resolve_modal_title: 'Отчёт о завершении ремонта',
    incident_notes_placeholder: 'Опишите проделанную работу (замена замка, сброс кода, ремонт дверцы)...',
    incident_tech_notes: 'Отчёт техника о ремонте',
    incident_reporter: 'Заявитель',
    incident_my_tasks: 'Мои назначенные задачи',
    incident_reported_success: 'Заявка успешно создана. Администратор и техник уведомлены!',
    tech_dashboard_title: 'Рабочее место техника',
    tech_dashboard_subtitle: 'Управление заявками на ремонт и техническое обслуживание локеров',
    tech_assigned_tasks: 'Назначено мне',
    tech_in_progress: 'В процессе ремонта',
    tech_resolved_today: 'Отремонтировано',
    tech_no_tasks: 'Нет назначенных задач. Всё исправно!',
    tech_task_card_floor: 'Этаж',
    tech_view_photo: 'Посмотреть фото поломки',
    tech_mark_progress_success: 'Задача взята в работу.',
    tech_resolve_success: 'Шкафчик отремонтирован! Студент и администратор получили уведомление.',
    ud_report_issue: 'Сообщить о поломке',
    ud_my_reports: 'Мои заявки на ремонт',
    ud_no_reports: 'У вас нет активных заявок на ремонт шкафчика.',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en');

  const switchLang = useCallback((newLang) => {
    setLang(newLang);
    localStorage.setItem('lang', newLang);
  }, []);

  const t = useCallback((key, params) => {
    let text = translations[lang]?.[key] || translations.en[key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, v);
      });
    }
    return text;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, switchLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
